parameters:
#    crud_crud.example.class: Crud\CrudBundle\Example

services:
#    crud_crud.example:
#        class: %crud_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
